server:
  port: ${URLCLEANER_PORT}

idealobridge:
  oAuth2ClientId: ${CLIENT_ID}
  oAuth2ClientSecret: ${CLIENT_SECRET}
  accessTokenURI: ${ACCESS_TOKEN_URI}
  apiUrl: ${API_URL}
  shopIDToRootUrlRoute: "rootUrl/"

spring:
  data:
      mongodb:
        host: ${MONGO_IP}
        port: ${MONGO_PORT}
        username: ${MONGO_URLCLEANER_USER}
        password: ${MONGO_PASSWORD}
        database: data